{"uid":"82b632080836bcf4","name":"test_update","fullName":"Test_Case.test_updateinfo#test_update","historyId":"19ac18c875853423f17308ce3c8fa87a","time":{"start":1667978814194,"stop":1667978814195,"duration":1},"status":"broken","statusMessage":"OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.","statusTrace":"def test_update():\n        # Take Input from User to update values\n    \n>       id = input(\"Which Information id would you like to update? \")\n\nTest_Case\\test_updateinfo.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <_pytest.capture.DontReadFromInput object at 0x00000193C93A8130>, args = ()\n\n    def read(self, *args):\n>       raise OSError(\n            \"pytest: reading from stdin while output is captured!  Consider using `-s`.\"\n        )\nE       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.\n\nvenv\\lib\\site-packages\\_pytest\\capture.py:192: OSError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.","statusTrace":"def test_update():\n        # Take Input from User to update values\n    \n>       id = input(\"Which Information id would you like to update? \")\n\nTest_Case\\test_updateinfo.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <_pytest.capture.DontReadFromInput object at 0x00000193C93A8130>, args = ()\n\n    def read(self, *args):\n>       raise OSError(\n            \"pytest: reading from stdin while output is captured!  Consider using `-s`.\"\n        )\nE       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.\n\nvenv\\lib\\site-packages\\_pytest\\capture.py:192: OSError","steps":[],"attachments":[{"uid":"2ab763cb094e2038","name":"stdout","source":"2ab763cb094e2038.txt","type":"text/plain","size":47}],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"stepsCount":0},"afterStages":[],"labels":[{"name":"parentSuite","value":"Test_Case"},{"name":"suite","value":"test_updateinfo"},{"name":"host","value":"DML-56MDLG3"},{"name":"thread","value":"31988-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Test_Case.test_updateinfo"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"82b632080836bcf4.json","parameterValues":[]}